server:
  port: 8083

spring:
  datasource:
    url: ${JDBC_HOST:jdbc:postgresql://localhost:5432/postgres}
    username: postgres
    password: postgres
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
  kafka:
    producer:
      bootstrap-servers: ${BOOTSTRAP_HOST:localhost:29092}

clients:
  lamoda:
    base-url: https://www.lamoda.ru/api/v1/product/get
