server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true

clients:
  lamoda:
    base-url: https://www.lamoda.ru/api/v1/product/get
